name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt

